---
title: "Plotly Graph"
author: "Cliff Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)
require(plotly)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


#### Code Source Inspiration
https://plotly.com/r/choropleth-maps/


```{r}
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')
colnames(df) <- c('Country')
head(df)

df2 <- read.csv('netflix_price.csv')

head(df2)

df3 <- merge(df, df2)
head(df3)

#rename columns
names(df3)[3] <- 'Code'
names(df3)[7] <- 'Cost_basic'
names(df3)[8] <- 'Cost_standard'
names(df3)[9] <- 'Cost_premium'



fig <- plot_ly(df3, type='choropleth', locations=df3$Code, z=df3$Cost_basic, text=df3$Country, colorscale="Blues")

# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)


fig <- fig %>% colorbar(title = 'Cost (US$)', tickprefix = '$')
fig <- fig %>% layout(
    title = 'Netflix Monthly Basic Subscription<br> Source: <a href="https://www.kaggle.com/prasertk/netflix-subscription-price-in-different-countries">Kaggle</a>'
  )

fig
```




  