---
title: "Nick's Graphic"
author: "Nick Beery"
date: "Spring 2022"
output: html_document
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = 'index.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 5.5, fig.width = 9.5)

library(plotly)
```

## Import Data
```{r}
data <- read.csv("USA_GDP_Annual.csv")
```
**Note**: All values are measured in millions of USD.

## Data Wrangling
### Column Types & Removing Commas
```{r}
# remove commas & convert to numeric
data$GDP <- as.numeric(gsub("," ,"" , data$GDP))
data$Consumption <- as.numeric(gsub("," ,"" , data$Consumption))
data$Investment <- as.numeric(gsub("," ,"" , data$Investment))
data$Net.Exports <- as.numeric(gsub("," ,"" , data$Net.Exports))
data$Government.Spending <- as.numeric(gsub("," ,"" , data$Government.Spending))
```

### Keep Certain Years
```{r}
# keep years that are multiples of 10
data10 <- subset(data, Year %% 10 == 0)
```

### Add Proportions
```{r}
# add proportion of consumption, investment, net exports, and government spending
data10 <- data10 %>% mutate(
  Consumption.prop = Consumption / GDP,
  Investment.prop = Investment / GDP,
  Net.Exports.prop = Net.Exports / GDP,
  Government.Spending.prop = Government.Spending / GDP
)
```

## Create *plotly* Graphic
### GDP by Year (Line)
```{r, echo=FALSE}
data %>%
  plot_ly() %>%
  add_lines(x = ~Year, y = ~GDP) %>%
  layout(title = "GDP by Year", yaxis = list(title = "GDP (millions of USD)"))
```

### GDP by Year (Bar)
```{r, warning=FALSE, echo=FALSE}
data10 %>%
  plot_ly() %>%
  add_bars(x = ~Year, y = ~GDP, color = ~Year) %>%
  layout(barmode = "stack", title = "GDP by Year", yaxis = list(title = "GDP (millions of USD)"))
```

### Components of GDP by Year (Stacked)
```{r, echo=FALSE}
data10 %>%
  plot_ly() %>%
  add_bars(x = ~Year, y = ~Consumption.prop, name = "Consumption") %>%
  add_trace(type = "bar", x = ~Year, y = ~Investment.prop, name = "Investment") %>%
  add_trace(type = "bar", x = ~Year, y = ~Net.Exports.prop, name = "Net Exports") %>%
  add_trace(type = "bar", x = ~Year, y = ~Government.Spending.prop, name = "Government Spending") %>%
  layout(barmode = "stack", title = "Components of GDP by Year", yaxis = list(title = "Proportion of GDP"))
```

### Components of GDP by Year (Group)
```{r, echo=FALSE}
data10 %>%
  plot_ly() %>%
  add_bars(x = ~Year, y = ~Consumption.prop, name = "Consumption") %>%
  add_trace(type = "bar", x = ~Year, y = ~Investment.prop, name = "Investment") %>%
  add_trace(type = "bar", x = ~Year, y = ~Net.Exports.prop, name = "Net Exports") %>%
  add_trace(type = "bar", x = ~Year, y = ~Government.Spending.prop, name = "Government Spending") %>%
  layout(barmode = "group", title = "Components of GDP by Year", yaxis = list(title = "Proportion of GDP"))
```

### Components of GDP by Year (Pie Charts)
```{r, echo=FALSE}
data10 %>%
  plot_ly() %>%
  add_bars(x = ~Year, y = ~Consumption.prop, name = "Consumption") %>%
  add_trace(type = "bar", x = ~Year, y = ~Investment.prop, name = "Investment") %>%
  add_trace(type = "bar", x = ~Year, y = ~Net.Exports.prop, name = "Net Exports") %>%
  add_trace(type = "bar", x = ~Year, y = ~Government.Spending.prop, name = "Government Spending") %>%
  layout(barmode = "group", title = "Components of GDP by Year", yaxis = list(title = "Proportion of GDP"))
```
