---
title: "Adam's Data-303 Visualization Project"
author: "Adam Ritsema (ajr58)"
date: "Spring 2022"
output: html_document
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = 'index.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(plotly)
library(readxl)
```

### Read in Data

```{r}
# Get the Data

food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# PLEASE NOTE TO USE 2020 DATA YOU NEED TO USE tidytuesdayR version ? from GitHub

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2020-02-18')
tuesdata <- tidytuesdayR::tt_load(2020, week = 8)


food_consumption <- tuesdata$food_consumption

food_consumption
```

### Data Wrangling

```{r}
food_consumption_total <- food_consumption %>%
  group_by(food_category) %>%
  summarize(total_consumption = sum(consumption),
            total_emission = sum(co2_emmission)) %>%
  mutate(food_type = case_when(food_category == "Pork" ~ "Animal Product",
                               food_category == "Poultry" ~ "Animal Product",
                               food_category == "Beef" ~ "Animal Product",
                               food_category == "Fish" ~ "Animal Product",
                               food_category == "Eggs" ~ "Animal Product",
                               food_category == "Milk - inc. cheese" ~ "Animal Product",
                               TRUE ~ "Non-Animal Product"))

food_consumption_total
```

### Visualization

```{r}
plot_ly(data = food_consumption_total,
        type = "treemap",
        labels = ~ food_category,
        values = ~ total_consumption)
```

