---
title: "Data 303 Projects"
date: "Spring 2022"
output: html_document
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = 'index.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
```

```{r load-data, include=FALSE}
lego_themes <- read_csv("data/themes.csv")
lego_sets <- read_csv("data/sets.csv")
```

```{r data-peak, include=FALSE}
head(lego_themes)
head(lego_sets)
```

```{r wrangle-merge, include=FALSE}
lego <- merge(lego_themes, lego_sets, by.x ="id", by.y ="theme_id", all.x = TRUE, all.y = FALSE)
```

```{r wrangle, include=FALSE}
head(lego)
lego_wrangle <- lego %>%
  group_by(name.x, year) %>%
  filter(grepl('Star Wars', name.x)) %>%
  summarise(n=n())
lego_wrangle
```


```{r vis, include=FALSE}
lego_highlight <- highlight_key(lego_wrangle, ~name.x)

base <- plot_ly(lego_highlight, color = I("black")) %>%
  group_by(name.x)

time_series <- base %>%
  group_by(name.x) %>%
  add_lines(x = ~year, y = ~n)

highlight(
  time_series, 
  on = "plotly_click", 
  selectize = TRUE, 
  dynamic = TRUE, 
  persistent = TRUE
)

```

# Lego Visualization

```{r vis2}
lego_plot <- base %>%
  summarise(sum = sum(n)) %>%
  add_markers(
    x= ~sum, 
    y = ~fct_reorder(name.x, sum),
    hoverinfo = "x+y"
  ) %>%
  layout(
    xaxis = list(title = "Year"),
    yaxis = list(title = "Number of Lego Sets")
  ) 

subplot(lego_plot, time_series, widths = c(.2, .8), titleX = TRUE) %>%
  layout(showlegend = FALSE) %>%
  highlight(on = "plotly_selected", dynamic = TRUE, selectize = TRUE, persistent = TRUE)
```

# Lego Set Data

```{r}
head(lego_wrangle)
```

From https://www.kaggle.com/rtatman/lego-database/version/1?select=themes.csv and was made merging themes.csv and sets.csv while filtering by themes containing 'Star Wars'

# References

https://plotly-r.com/index.html

# Reflection


* [plotly projects](plotly-projects)
